version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./code/default:/var/www/default
    ports:
      - "90:80"
    depends_on:
      - phpfpm72
  phpfpm72:
    restart: always
    build:
      context: .
      dockerfile: php72.Dockerfile
    volumes:
      - ./code/default:/var/www/default
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "33061:3306"
    expose:
      - 33061
    environment:
      MYSQL_HOST: root
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8004:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_PASSWORD: admin
    depends_on:
      - mysql